GET http://localhost:3000/users/5
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlBlZHJvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY2MjA3OTAxfQ.F0fPTS_U9gfi7cQtNwi11txHtWaGacWIG5foYRwy2vU

###

GET http://localhost:3000/users?search=&page=1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlBlZHJvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY2MjAwMTg0fQ.wby1mMzDHIHfld_2yyYiDZbL2reNQkzC_s290pBWIQw

### 

GET http://localhost:3000/products/10


###

PATCH http://localhost:3000/users/2
Content-Type: application/json

{
 "password": "1234556"
}

###
DELETE http://localhost:3000/users/3

###

GET http://localhost:3000/products?search=&page=1

###

POST http://localhost:3000/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlBlZHJvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY2MjAwMTg0fQ.wby1mMzDHIHfld_2yyYiDZbL2reNQkzC_s290pBWIQw

{
 "name": "Mario Kart",
 "price": 300.00,
 "stock": "71"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
 "name": "Kaio",
 "lastname": "Gomes",
 "email": "example1@gmail.com",
 "password": "senha"
}

### 

POST http://localhost:3000/auth/login
Content-Type: application/json

{
 "email": "pedro@gmail.com",
 "password": "123456"
}

### 
PATCH http://localhost:3000/products/6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlBlZHJvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY2MjA3OTAxfQ.F0fPTS_U9gfi7cQtNwi11txHtWaGacWIG5foYRwy2vU

{
 "name": "Garrafa de água"
}

###

DELETE http://localhost:3000/users/8
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlBlZHJvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY2MjA3OTAxfQ.F0fPTS_U9gfi7cQtNwi11txHtWaGacWIG5foYRwy2vU

### 
PATCH http://localhost:3000/users/4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlBlZHJvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY2MjA3OTAxfQ.F0fPTS_U9gfi7cQtNwi11txHtWaGacWIG5foYRwy2vU

{
 "lastname": "Santos"
}
###
POST http://localhost:3000/users/4/order
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlBlZHJvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY2MjA3OTAxfQ.F0fPTS_U9gfi7cQtNwi11txHtWaGacWIG5foYRwy2vU


 [
    {"productId": 9, "quantity": 2}
 ]

###
GET http://localhost:3000/users/4/orders
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlBlZHJvIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzY2MjA3OTAxfQ.F0fPTS_U9gfi7cQtNwi11txHtWaGacWIG5foYRwy2vU