GET http://localhost:3000/users/100

###

GET http://localhost:3000/users?search=pe&page=1

###

POST http://localhost:3000/users
Content-Type: application/json

{
 "name": "João",
 "lastname": "Henrique",
 "email": "joaohenrique@gmail.com",
 "password": "henrique123"
}

###

PATCH http://localhost:3000/users/3
Content-Type: application/json

{
 "name": "Fernando"
}

###
DELETE http://localhost:3000/users/3

###

GET http://localhost:3000/products?search=mouse&page=2

###

POST http://localhost:3000/products
Content-Type: application/json

{
 "name": "Camiseta",
 "price": 129.99,
 "stock": "2"
}