GET http://localhost:3000/users/3

###

POST http://localhost:3000/users
Content-Type: application/json

{
 "name": "João",
 "lastname": "Henrique",
 "email": "joaohenrique@gmail.com",
 "password": "henrique123"
}

###

PATCH http://localhost:3000/users/3
Content-Type: application/json

{
 "name": "Fernando"
}

###
DELETE http://localhost:3000/users/3